# Part 4

In [1]:
import pandas as pd
import numpy as np
from final.garch import get_garch_parameters

### ii. Fit GARCH(1, 1)

First we read in the data.

In [2]:
stock = pd.read_parquet('../data/stock.parquet')
stock.head()

           symbol   close  adj_close  dividend  split
date
2010-01-04   AAPL  214.01   6.418261       0.0    1.0
2010-01-05   AAPL  214.38   6.429358       0.0    1.0
2010-01-06   AAPL  210.97   6.327090       0.0    1.0
2010-01-07   AAPL  210.58   6.315394       0.0    1.0
2010-01-08   AAPL  211.98   6.357381       0.0    1.0

Now we calculate log returns.

In [3]:
stock['log_ret'] = np.log(stock['adj_close']).diff()
stock.head()

           symbol   close  adj_close  dividend  split   log_ret
date
2010-01-04   AAPL  214.01   6.418261       0.0    1.0       NaN
2010-01-05   AAPL  214.38   6.429358       0.0    1.0  0.001727
2010-01-06   AAPL  210.97   6.327090       0.0    1.0 -0.016034
2010-01-07   AAPL  210.58   6.315394       0.0    1.0 -0.001850
2010-01-08   AAPL  211.98   6.357381       0.0    1.0  0.006626

The GARCH(1, 1) process is modeled as $$\sigma^2_t = \alpha_0 + \alpha_1 u^2_{t-1}+ \beta_1 \sigma^2_{t-1}.$$ My GARCH implementation estimates these parameters using Maximum Likelihood Estimation.

In [4]:
res = get_garch_parameters(stock['log_ret'][1:])

c:\Users\rahul\anaconda3\Lib\site-packages\scipy\optimize\_slsqp_py.py:435: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

The parameter estimates are shown below.

In [5]:
alpha_0, alpha_1, beta_1 = res
print("Alpha_0 estimate:", alpha_0)
print("Alpha_1 estimate:", alpha_1)
print("Beta_1 estimate:", beta_1)

Alpha_0 estimate: 0.16156477096295724
Alpha_1 estimate: 0.09477714711082316
Beta_1 estimate: 0.8545753501700564